### ISSUE TITLE
Add sentry support

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#31]
We should be sure to add sentry before we go live so we can debug errors. We'll need to work together to get it set up in Sentry, and then get a DSN that we can put into our settings. CL has an example of how to do this. It's pretty easy.

**Comment by mlissner** [comment]
In CL we have sentry.py:

```
import environ
import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration

env = environ.FileAwareEnv()
SENTRY_DSN = env("SENTRY_DSN", default="")


if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            CeleryIntegration(),
            DjangoIntegration(),
            RedisIntegration(),
        ],
        ignore_errors=[KeyboardInterrupt],
    )
```

Their docs recommend:

```
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn="A LONG URL HERE",
    integrations=[
        DjangoIntegration(),
    ],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)
```

I don't think we want to send PII to Sentry, but we can do the traces; why not.

I put our DSN into the bot settings, like CL has it.

**Comment by mlissner** [comment]
Oh, we also have a route to trigger/test Sentry, as their docs recommend:

urls.py:
```
from django.urls import path

urlpatterns = [
    path("sentry/error/", sentry_fail, name="sentry_fail"),
]
```

views.py:
```
def sentry_fail(request: HttpRequest) -> HttpResponse:
    division_by_zero = 1 / 0
```

 - [ ] And we have a CI task to generate sentry releases

```yml
name: sentry-release

on:
  push:
    branches:
      - '**'

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: freelawproject
          SENTRY_PROJECT: courtlistener
        with:
          version: ${{ github.sha }}
          environment: prod
```

Sorry. The bad news is we're good at being thorough. The good news is we're good at being thorough.
